language: php
php:
  - "7.0"

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit -c dev/tests/phpunit.xml.dist --coverage-clover build/logs/clover.xml
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls
